const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
const DELETE_AUTHOR_OPTIMISTIC = "DELETE_AUTHOR_OPTIMISTIC";
const LOAD_AUTHOR_SUCCESS = "LOAD_AUTHOR_SUCCESS";
const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";

export default {
  CREATE_AUTHOR_SUCCESS,
  DELETE_AUTHOR_OPTIMISTIC,
  LOAD_AUTHOR_SUCCESS,
  UPDATE_AUTHOR_SUCCESS
};
